// export const backgroundColorMain = '#000'
// export const textColorMain = '#7a61bc'
// export const textColorBlack = '#000'
// export const textColorMainVariant1 = 'rgba(255, 255, 255, 0.8)'
// export const textColorMainVariant2 = 'rgba(255, 255, 255, 0.6)'
// export const textColorMainVariant3 = 'rgba(255, 255, 255, 0.7)'
// export const textColorMainVariant4 = 'rgba(254, 254, 254, 1)'
// export const textColorMainVariant5 = 'rgba(51, 51, 51, 1)'
// export const primaryColor = '#B7A9DA'
// export const secondaryColor = '#edeeff'
// export const primaryColorLight = '#ECE8F6'
// export const boxLightGrey = 'rgba(255, 255, 255, 0.1)'
// export const boxGrey = 'rgba(255, 255, 255, 0.2)'
// export const blueColor = '#4754F0'
// export const greenColor = '#9AFD98'
// export const greenColorLight = 'rgba(154, 253, 152, 0.1)'
// export const textColorLighGrey = '#F1F2F4'
// export const textColorLightGrey = '#DADADA'
// export const textColorLightGreyVariant = 'rgba(218, 218, 218, 0.7)'
// export const purpleColor = '#AE94FB'
// export const purpleColorLight = 'rgba(174, 148, 251, 0.1)'
// export const liveColor = 'rgba(254, 99, 99, 1)'
// export const redColor = '#FE6363'
// export const redColorVariant = '#FF5C43'
// export const pinkColor = '#FD9898'
// export const greyColor = '#D9D9D9'
// export const greyColorVariant = 'rgba(217, 217, 217, 0.9)'
// export const borderColorMain = 'rgba(255, 255, 255, 0.4)'
// export const textColorLight = '#ADADAD'
// export const transparentColor = 'rgba(0,0,0,0)'
// export const greenishYellowColor = 'rgba(224, 251, 148, 1)'
// export const greenishYellowVariant = 'rgba(224, 251, 148, 0.1)'
// export const textColorBlackVariant1 = 'rgba(33, 33, 33, 1)'
// export const textColorBlackVariant2 = 'rgba(33, 33, 33, 0.7)'

// // export const primaryColor = '#B7A9DA'

export const backgroundColorMain = '#F0F4F8' // Light grayish blue
export const bgColorSecondary = '#5E60CE' // Vivid indigo
export const accentColor = '#64DFDF' // Bright cyan
export const whiteColor = '#FFFFFF' // Pure white
export const blackColor = '#2D3748' // Dark slate gray
export const textColorPrimary = '#1A202C' // Very dark gray
export const textColorSecondary = '#4A5568' // Medium gray
export const successColor = '#48BB78' // Green
export const warningColor = '#ED8936' // Orange
export const errorColor = '#E53E3E' // Red

// export const backgroundColorMain = '#F7F9FC' // Very light blue-gray
// export const bgColorSecondary = '#3A86FF' // Vivid blue
// export const accentColor = '#FF006E' // Vivid pink
// export const whiteColor = '#FFFFFF' // Pure white
// export const blackColor = '#1E2A3B' // Very dark blue-gray
// export const textColorPrimary = '#2D3748' // Dark slate gray
// export const textColorSecondary = '#718096' // Medium gray
// export const successColor = '#10B981' // Emerald green
// export const warningColor = '#FBBF24' // Amber
// export const errorColor = '#EF4444' // Red
